{
 "title": "abc2",
 "description": "lskjdf lkjdfsl",
 "tags": [ "lft" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Upstreams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Call Count",
   "type": "graph",
   "description": "Number of times each endpoint has been hit",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(application.*.*.*.abc2.controller.*.*.*.*.count, 8, 9)"
    }
   ]
  },
  {
   "title": "Response Code (400s & 500s)",
   "type": "graph",
   "description": "Response code for each endpoint (400s & 500s)",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(application.*.*.*.abc2.controller.*.*.*.*.{4xx,5xx}.count, 8, 9, 10)"
    }
   ]
  },
  {
   "title": "Response Code",
   "type": "graph",
   "description": "Response code for each endpoint",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(application.*.*.*.abc2.controller.*.*.*.*.*.count, 8, 9, 10)"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "graph",
   "description": "Response Times Across All Endpoints",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(avg(application.*.*.*.abc2.controller.*.*.*.*.mean), 'Mean')"
    },
    {
     "target": "alias(avg(application.*.*.*.abc2.controller.*.*.*.*.p95), ' P95')"
    },
    {
     "target": "alias(avg(application.*.*.*.abc2.controller.*.*.*.*.p99), 'P99')"
    }
   ]
  },
  {
   "title": "Mean Response Times Per Handler",
   "type": "graph",
   "description": "Mean Response Times Across All Endpoints",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(application.*.*.*.abc2.controller.*.*.*.*.mean, 8, 9)"
    }
   ]
  },
  {
   "title": "P95 Response Times Per Handler",
   "type": "graph",
   "description": "P95 Response Times Across All Endpoints",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(application.*.*.*.abc2.controller.*.*.*.*.p95, 8, 9)"
    }
   ]
  },
  {
   "title": "P99 Response Times Per Handler",
   "type": "graph",
   "description": "P99 Response Times Across All Endpoints",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(application.*.*.*.abc2.controller.*.*.*.*.p99, 8, 9)"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Parcel DB: Request count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(application.*.*.*.abc2.Database.*.*.count, 6, 7)"
    }
   ]
  },
  {
   "title": "Parcel DB: Response Time (P99)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(application.*.*.*.abc2.Database.*.*.p99, 6, 7)"
    }
   ]
  },
  {
   "title": "Parcel DB: Response Time (P95)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(application.*.*.*.abc2.Database.*.*.p95, 6, 7)"
    }
   ]
  },
  { "title": "Downstreams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Call Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(application.*.*.*.abc2.downstream.*.*.count, 6, 7)"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(application.*.*.*.abc2.downstream.*.*.status.*.count, 6, 7, 9)"
    }
   ]
  },
  {
   "title": "Response Times P95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(application.*.*.*.abc2.downstream.*.*.p95, 6, 7)"
    }
   ]
  },
  { "title": "Kafka Consumer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Kafka Consumer Event Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(application.*.*.*.abc2.Kafka.Consumer.*.count, 4, 7)"
    }
   ]
  },
  {
   "title": "Kafka Consumer Event Processing Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(application.*.*.*.abc2.Kafka.Consumer.*.mean, 8)"
    },
    {
     "target": "aliasByNode(application.*.*.*.abc2.Kafka.Consumer.*.p95, 8)"
    },
    {
     "target": "aliasByNode(application.*.*.*.abc2.Kafka.Consumer.*.p99, 8)"
    }
   ]
  },
  {
   "title": "Kafka Consumer Lag Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(application.*.*.*.abc2.Kafka.Consumer.*.Lag.mean, 9)"
    },
    {
     "target": "aliasByNode(application.*.*.*.abc2.Kafka.Consumer.*.Lag.p95, 9)"
    },
    {
     "target": "aliasByNode(application.*.*.*.abc2.Kafka.Consumer.*.Lag.p99, 9)"
    }
   ]
  },
  { "title": "Kafka Producer Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Kafka Send Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(application.*.*.*.abc2.Kafka.Producer.*.*.Send.mean, 7, 10)"
    },
    {
     "target": "aliasByNode(application.*.*.*.abc2.Kafka.Producer.*.*.Send.p95, 7, 10)"
    },
    {
     "target": "aliasByNode(application.*.*.*.abc2.Kafka.Producer.*.*.Send.p99, 7, 10)"
    }
   ]
  },
  {
   "title": "Kafka Send Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(application.*.*.*.abc2.Kafka.Producer.*.*.Failure.count, 7)"
    }
   ]
  }
 ]
}