{
 "title": "log-david-svc",
 "description": "This is David's service",
 "tags": [ "lft" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Upstreams", "type": "row", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Call Count",
   "type": "graph",
   "description": "Number of times each endpoint has been hit",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(application.*.*.*.log-david-svc.controller.*.*.*.*.count, 8, 9)"
    }
   ]
  },
  {
   "title": "Response Code (400s & 500s)",
   "type": "graph",
   "description": "Response code for each endpoint (400s & 500s)",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(application.*.*.*.log-david-svc.controller.*.*.*.*.{4xx,5xx}.count, 8, 9, 10)"
    }
   ]
  },
  {
   "title": "Response Code",
   "type": "graph",
   "description": "Response code for each endpoint",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(application.*.*.*.log-david-svc.controller.*.*.*.*.*.count, 8, 9, 10)"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "graph",
   "description": "Response Times Across All Endpoints",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(avg(application.*.*.*.log-david-svc.controller.*.*.*.*.mean), 'Mean')"
    },
    {
     "target": "alias(avg(application.*.*.*.log-david-svc.controller.*.*.*.*.p95), ' P95')"
    },
    {
     "target": "alias(avg(application.*.*.*.log-david-svc.controller.*.*.*.*.p99), 'P99')"
    }
   ]
  },
  {
   "title": "Mean Response Times Per Handler",
   "type": "graph",
   "description": "Mean Response Times Across All Endpoints",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(application.*.*.*.log-david-svc.controller.*.*.*.*.mean, 8, 9)"
    }
   ]
  },
  {
   "title": "P95 Response Times Per Handler",
   "type": "graph",
   "description": "P95 Response Times Across All Endpoints",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(application.*.*.*.log-david-svc.controller.*.*.*.*.p95, 8, 9)"
    }
   ]
  },
  {
   "title": "P99 Response Times Per Handler",
   "type": "graph",
   "description": "P99 Response Times Across All Endpoints",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(application.*.*.*.log-david-svc.controller.*.*.*.*.p99, 8, 9)"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Parcel DB: Request count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(application.*.*.*.log-david-svc.Database.*.*.count, 6, 7)"
    }
   ]
  },
  {
   "title": "Parcel DB: Response Time (P99)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(application.*.*.*.log-david-svc.Database.*.*.p99, 6, 7)"
    }
   ]
  },
  {
   "title": "Parcel DB: Response Time (P95)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(application.*.*.*.log-david-svc.Database.*.*.p95, 6, 7)"
    }
   ]
  }
 ]
}